version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - VERSION=1.0.0
  build:
    commands:
      - echo Build started on `date`
      - echo "Project Version -> $VERSION"
      - mvn test
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --s3-bucket michalrozyckibucket3 --template-file template.yml --output-template-file outputSamTemplate.yml
      - ls -la target
artifacts:
  files:
    - build/libs/michalrozycki-$VERSION.jar
    - outputSamTemplate.yml
